# Generated by Django 3.0 on 2019-12-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledInterview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_of_times', models.TextField()),
            ],
            options={
                'verbose_name': 'scheduled',
            },
        ),
    ]
