# Generated by Django 3.0 on 2019-12-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0002_scheduledinterview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledInterview',
        ),
    ]
